### ISSUE TITLE
Having trouble getting the class of a click event target using jQuery

### ISSUE THREAD

**Issue by TilinC** [TilinC/Checkers#1]
My pieces are divs with two classes: `piece` and `black` or `red` 
<br>
I would like my `move` function to check whether the class of a click event's target includes 'red' or 'black'.  
<br>
The value of currentPlayer is 'black'
<br>
I tried: 
```js
if (event.target.attr('class') === currentPlayer.color)
```
<br>
```js
if (event.target.class === currentPlayer.color)
```
<br>
```js
if (($event.target.attr('class')) === currentPlayer.color)
```

**Comment by syang019** [comment]
Used $(this).attr to fix the selection.
