### ISSUE TITLE
filter method returning an array whose object's value is sometimes undefined but at other times defined when reloading browser page

### ISSUE THREAD

**Issue by TilinC** [TilinC/Checkers#2]
Here's the relevant code: 
```js
// Retrieves location of player's selection, so long as player selected one of their pieces
var selectPieceToMove = function(event) {
  if ($(this).hasClass(currentPlayer.color)) {
    // gets location of the selected piece
    var selectedPieceID = $(this).parent().attr('id');
    selectedPieceRow = parseInt(selectedPieceID.split(",")[0]);
    selectedPieceCol = parseInt(selectedPieceID.split(",")[1]);

    //gets the type of the selected piece
    selectedPieceType = currentPlayer.pieces.filter(hasRowAndCol);
    selectedPieceType = selectedPieceType[0];
    selectedPieceType = selectedPieceType.type;

    console.log(currentPlayer.name + ' selected a ' + selectedPieceType + ' piece at row: ' + selectedPieceRow + ', col: ' + selectedPieceCol);
  } else return false;
};
```
When I test this, selectedPieceType is sometimes the right value, but upon refreshing the page and playing again, logs as `undefined`.  Or vice versa-- sometimes I get an error but when refreshing the page, don't get an error.

For example...

![working](http://i.imgur.com/TwWQ41P.png)
<br>
and on reloading (and not making any changes to the source code)...
<br>
![not working](http://i.imgur.com/Atz5FFp.png)

**Comment by h4w5** [comment]
Tiffany! :heart:!!!! What a great issue! What well-written, well-structured code! Fantastic!

This is a really fun error. Read it again, it's telling you everything. On line 96, you are calling `.type` on a variable whose contents is `undefined`. Which means that `selectedPieceType` is `undefined`.

Which also means that `selectedPieceType[0]` is `undefined`, which means that:

```javascript
currentPlayer.pieces.filter(hasRowAndCol);
//=> sometimes is returning undefined
```

So, we haven't really covered `.filter`, but if you understand what's happening with it (it goes through a collection and gets the pieces for which the given callback returns `true`), you can make further assumptions. *If it sometimes works,* that means that you've written it's code correctly. Instead, sometimes `currentPlayer.pieces` actually holds the information your expecting, and sometimes not.

If you haven't already solved this, come to me and I'll help you debug this first thing today!
